### ISSUE TITLE
パーマリンクの検討

### ISSUE THREAD

**Issue by lunaluna** [wpzoomup/website#18]
**現状はすべてのページでカスタムスラッグを入力している**

- その必要があるか？
    - そもそもそうなった経緯は？
- 仮に変更する場合
    - そのコストは？
    - どのスラッグの形式にする？

**Comment by lunaluna** [comment]
- スラッグの命名ルールを決める

**Comment by megane9988** [comment]
とりあえず既存になるべく揃える方向で！
