### ISSUE TITLE
新しいサーバを取得する

### ISSUE THREAD

**Issue by megane9988** [wpzoomup/website#2]
- サーバホスティングの決定
    - Xserver
    - さくら
    - Lollipop
- ホスティングの契約
- アカウント作成

**Comment by Shizumi** [comment]
### 料金プラン比較表
<table>
	<tr>
		<th>サーバ会社名</th>
		<th>プラン名</th>
		<th>料金(単年,税込)</th>
		<th>初期料金</th>
		<th>サーバ容量</th>
		<th>仕様リンク</th>
	</tr>
	<tr>
		<th>XSERVER</th>
		<td>X10</td>
		<td>13,200円</td>
		<td>3,000円</td>
		<td>200GB</td>
		<td><a href="https://www.xserver.ne.jp/functions/">参考</a></td>
	</tr>
	<tr>
		<th>さくら</th>
		<td>スタンダード</td>
		<td>5,238円</td>
		<td>1,048円</td>
		<td>100GB</td>
		<td><a href="https://www.sakura.ne.jp/plans.html">参考</a></td>
	</tr>
	<tr>
		<th>LOLIPOP</th>
		<td>スタンダード</td>
		<td>6,600円</td>
		<td>1,650円</td>
		<td>120GB</td>
		<td><a href="https://lolipop.jp/pricing/#plan-comparison">参考</a></td>
	</tr>
</table>

### 個人的所感
**XSERVER**
若干オーバーキル感があるかなと思います。
**さくら**
ちょうどよいのかと感じますが、個人的にあまり使用したことがないため、使用されている方がいらっしゃればメリットデメリットが知りたいです。（WP CLIが最初から入ってるとか良いなぁと思う）
**LOLIPOP**
ハイスピードプランというもう一つ上のプランもありますが、WebサーバがLiteSpeedであり、WordPressに最適化されてると謳われているもののちょっと普段と使用感が異なりそうで不安（カスタマイザーとかのブロック解除がホスティング会社とのやり取りが必要になるなどは把握済み）

**Comment by nukaga** [comment]
比較表ありがとうございます！わかりやすい！
XSERVERさん独自ドメイン１個使えるのメリットだと思うんですけど、今回は別で取っているのでそのメリットが活きないんですよね。そうなるとしずみさんの仰るとおりそこまでサーバースペック高くなくてもいいかなというように思いました。
あ、あと忘れてたんですけど、 @ShinichiNishikawa さんの管理してくださってるサーバーの中にはWP ZoomUPのMauticも入っていたように記憶しています。現状私の認識では使えていないのですが。一緒にお引っ越しするか決めた方が良いかも。( https://ma.wpzoomup.com/s/login )

**Comment by Shizumi** [comment]
独自ドメイン無料は確かに魅力的ですが、gTLDが結構ニッチだったりするのでｗ
テストドメインとして取得するというのもありかなとは思いますが、サブドメインでテストドメイン設定しても全く問題ないかなと思っています。
あとは、価格差を考えるとドメイン代払ったほうが結果的に安価ではありますね。

Mauticについても一応一緒に引っ越しする方向で考えていました（言い忘れ）

**Comment by Ippey** [comment]
|ω・`）

さくら：MySQL 5.7
ロリポ：MySQL 5.6

5.7にあがるとパフォーマンスも向上するので、そのへん考慮してもさくらの方がよいですね。
さくら、CoderDojoのサイトで使っていますが、とくに問題ないです。

**Comment by Shizumi** [comment]
@Ippey さんありがとうございます！！！

さくらが良いかもしれませんね〜

**Comment by megane9988** [comment]
こちらさくらでどうでしょう？
@ShinichiNishikawa

**Comment by ShinichiNishikawa** [comment]
まったく問題ございません！
出遅れてごめんなさい。

**Comment by Shizumi** [comment]
@ShinichiNishikawa さん
ありがとうございます！！
ではサーバ契約進めます！

**Comment by Shizumi** [comment]
申し込み、契約完了しました！

各種情報の共有方法をどうしましょうかね…


@megane9988 Issueのクローズ権限を私持ってないようなのでそのままです！

**Comment by megane9988** [comment]
無事に完了
書いたら完了ください
@Shizumi
