### ISSUE TITLE
Webマーケティング目線で対応する内容の共有

### ISSUE THREAD

**Issue by megane9988** [wpzoomup/website#26]

**Comment by ghost** [comment]
ひとまず今できることとして、WP ZoomUPサイトの流入状況が俯瞰できるようにしておき、今後サイト分析や改善立案をできるようにしようと思い、↓を作りました。
https://datastudio.google.com/reporting/271ca391-ddc7-4377-a60a-4e3958e3a068

**Comment by megane9988** [comment]
@osamunize ありがとうございます！、では一旦これでクローズします！
