### ISSUE TITLE
GTMタグの挿入

### ISSUE THREAD

**Issue by lunaluna** [wpzoomup/website#27]
https://docs.google.com/document/d/1mdDj8ttozOjgJag_OkH1Zf-WYhz1yRqdyLPyROCD000/edit

**Comment by megane9988** [comment]
おそらくSnow Monkeyのカスタマイザーで提供してくれる専用の入力枠にGTMのID的なものだけいれると、それだけで良さそうかとおもいます！

**Comment by megane9988** [comment]
@osamunize 
スノーモンキーのカスタマイズ経由でステージング側に入れています。おそらくこれで問題ないと思うのですが、ご確認くださいませ

**Comment by megane9988** [comment]
おそらく入ったと思うので、公開後見てみましょう！
