### ISSUE TITLE
ログ関連のファイルをどう扱うか

### ISSUE THREAD

**Issue by megane9988** [wpzoomup/website#39]

**Comment by megane9988** [comment]
各種ログをなるべく手数なく、アップしておきたい

- テキストファイルやエクセルファイル、画像、zipなどなどたくさんのファイル種類がある
- 都度、ファイル整形したりページを作成するのは工数が増えてしまう。
- Google Drive内に誰でもアクセスできるディレクトリをつくっておき、イベントごとにディレクトリをつくって、そちらにすべてのログファイルを入れておけばよさそう

**Comment by lunaluna** [comment]
- これまでのログを Google Driveにアップロードする
