### ISSUE TITLE
投稿タイプSpeakerをPersonに変更する

### ISSUE THREAD

**Issue by megane9988** [wpzoomup/website#45]
## 投稿タイプ
person

## カスタムタクソノミー
role
	- Speaker
	- Staff
	- Contributor

## Personの投稿タイプで利用するカスタムフィールド

- Twitterアカウント
- ウィッシュリスト
- リンクしたいURL(タイトルとURLの2つの入力枠で繰り返しフィールド)

**Comment by rocket-martue** [comment]
- 投稿タイプSpeakerをPersonに変更
- カスタム投稿タイプのアイコンをそれぞれ変更

**Comment by rocket-martue** [comment]
カスタムタクソノミー role を設定して、以下のロールを登録しました。
- Speaker
- Staff
- Contributor

**Comment by megane9988** [comment]
ありがとうございます！！
