### ISSUE TITLE
フッターのSNSの見栄えを変える

### ISSUE THREAD

**Issue by megane9988** [wpzoomup/website#56]
- タイトルを入れる
- SNSのアイコンにconnpassを含める
- 見栄えをデザインに合わせる

**Comment by rocket-martue** [comment]
WPZoomUP Customize Styles に、connpass アイコンを表示させるコードを追加。
アイコンの表示サイズを変更。

**Comment by rocket-martue** [comment]
コピーライト
`© 2018 WP ZoomUP. Powered by <a href="https://wordpress.org/" target="_blank">WordPress</a> &amp; <a href="https://snow-monkey.2inc.org/" target="_blank">Snow Monkey theme</a>.`
© 2018 WP ZoomUP. Powered by WordPress & Snow Monkey theme.
