### ISSUE TITLE
サイトマップを作成する

### ISSUE THREAD

**Issue by megane9988** [wpzoomup/website#6]

**Comment by tnktn** [comment]
ワイヤー作成時に必要なページも変わってくるかもしれませんがいったんまとめてみました。
現行サイトのデータを極力生かしたいのはありますが削ってよさそうなページも結構あると思ってます。

・サイトマップ案
https://docs.google.com/presentation/d/1lKyvm7ZsvTrWncLHnf17T5Pxj4hxGRsGgxiDyufGKlY/edit?usp=sharing

・ページリスト（リニューアル後＆現行）
https://docs.google.com/spreadsheets/d/105Ytc_2COwO1nWNJljmoyWWzivDwX3v3aHlT-TQG3iE/edit?usp=sharing

**Comment by megane9988** [comment]
すごい！さすが！ばっちりしっかり

**Comment by ShinichiNishikawa** [comment]
サイトマップとページリストに思ったところコメントを残しました。

特に、ページリストの「リニューアル後」タブ。ちょっと思ったことをメモしてみた、くらいのものなので、議論の参考にしたいです。
https://docs.google.com/spreadsheets/d/105Ytc_2COwO1nWNJljmoyWWzivDwX3v3aHlT-TQG3iE/edit#gid=0

**Comment by tnktn** [comment]
ありがとうございます！
ワイヤーを引く際に同意情報を掲載するかもっと詰めたいですね。

リニューアル後のページリスト案は最低限欲しいのかなぁ、というページのみに結構削ってあります。（商品一覧なくしたりとか）
現行の公開してるページの中にスポンサー募集フォームとかがあったりするので使うのなら再利用するかも。
