### ISSUE TITLE
【要望】固定ページ「お品書き」の編集画面からブロックを追加したい

### ISSUE THREAD

**Issue by lunaluna** [wpzoomup/website#61]

**Comment by lunaluna** [comment]
「投稿・お品書きを呼び出しているブロック」のあとにブロックが追加できないようです。

急ぎではないので9/6以降お手すきの際にご確認いただければ大丈夫です。

**Comment by rocket-martue** [comment]
最新のお品書きを表示するブロックを WPZ Menu Blocks から Lazy Blocks に変更しました。
ブロックの追加ができるようになっています。
