### ISSUE TITLE
よその（シリーズ系）イベントのウェブサイトを見てみる

### ISSUE THREAD

**Issue by megane9988** [wpzoomup/website#7]
URLを集める

CSS nite
DIST
SACCS

**Comment by ShinichiNishikawa** [comment]
トップページのスクショとってFigmaに入れました。

https://www.figma.com/file/EyiUc1GDLpudLSUZuFmUl9/Web-site-renewal?node-id=64%3A2

最初にランディングした人にどうしても伝わらないといけない最小の情報にする、ということだと、CSS nite も DISTもだいぶ絞れていて機能的だと思いました。

その上でなのですが、

* 雰囲気が伝わらない ≒ 顔が見えない？
    * ついでに触れるとここで見えるべき顔は運営者だけではなく、参加者も含むんだろうな、と思う。
* 歓迎されてる？
* 参加方法は若干わかりにくい

という感想です。
